//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public int AuctionId { get; set; }
        public int ItemId { get; set; }
        public decimal StartPrice { get; set; }
        public decimal CurrentPrice { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime LastBid { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
