//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auction
    {
        public Auction()
        {
            this.Bids = new HashSet<Bid>();
        }
    
        public int AuctionId { get; set; }
        public int ItemId { get; set; }
        public decimal StartPrice { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public short Status { get; set; }
        public decimal CurrentPrice { get; set; }
        public Nullable<int> BidderId { get; set; }
        public Nullable<System.DateTime> LastBiddedAt { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ICollection<Bid> Bids { get; set; }
    }
}
