//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.Auctions = new HashSet<Auction>();
        }
    
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal ItemStartPrice { get; set; }
        public string ItemDescription { get; set; }
        public byte[] ItemImage { get; set; }
        public int SellerId { get; set; }
    
        public virtual ICollection<Auction> Auctions { get; set; }
        public virtual User User { get; set; }
    }
}
